name: Build and publish crl-interactivesession to PyPI

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Build and publish crl-interactivesession to PyPI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install build
        run: >-
          python -m
          pip install
          setuptools
          --user
      - name: Build a binary wheel and a source tarball
        run: python setup.py sdist
      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}
