name: pre-merge

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - name: 2.7
            toxenv: py27,pylint27
          - name: 3.6
            toxenv: py36
          - name: 3.7
            toxenv: py37,pylint37,docs,doctest
          - name: 3.8
            toxenv: py38
          - name: 3.9
            toxenv: py39
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version.name }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version.name }}
      - name: Install tox
        run: python -m pip install tox
      - name: Run tests with tox
        run: python -m tox -e "${{ matrix.python-version.toxenv }}"
